export const productData = [
  // Agricultural Tools
  {
    id: "prod-001",
    name: "Electric Grass Cutter",
    image: "/electric grass cutter.png",
    price: "Rs. 12,500",
    isNew: true,
    rating: 4.7,
    reviews: 42,
    description:
      "Professional-grade electric grass cutter with extended battery life and ergonomic design. Perfect for maintaining lawns and gardens of all sizes.",
    features: [
      "Powerful 1200W motor for efficient cutting",
      "Adjustable cutting height from 20mm to 70mm",
      "Lightweight design for easy maneuverability",
      "Rechargeable lithium-ion battery with 2-hour runtime",
      "Foldable handle for compact storage",
    ],
    specifications: {
      "Motor Power": "1200W",
      "Cutting Width": "38cm",
      "Grass Box Capacity": "40L",
      Weight: "12kg",
      Battery: "40V Lithium-ion",
      "Charging Time": "1.5 hours",
      Warranty: "2 years",
    },
    availability: "In Stock",
    category: "agricultural",
  },
  {
    id: "prod-002",
    name: "Chainsaw",
    image: "/man-with-chainsaw-cutting-tree-t.png",
    price: "Rs. 18,900",
    isPopular: true,
    rating: 4.8,
    reviews: 76,
    description:
      "Heavy-duty chainsaw designed for professional use. Features a powerful engine and durable construction for tackling tough cutting jobs.",
    features: [
      "High-performance 58cc engine",
      "20-inch bar length for versatile cutting",
      "Anti-vibration system for comfortable operation",
      "Automatic chain oiler for maintenance",
      "Quick-stop chain brake for safety",
    ],
    specifications: {
      Engine: "58cc, 2-stroke",
      "Bar Length": "20 inches",
      "Chain Pitch": "3/8 inch",
      "Fuel Tank Capacity": "0.7L",
      "Oil Tank Capacity": "0.4L",
      Weight: "5.6kg",
      Warranty: "1 year",
    },
    availability: "In Stock",
    category: "agricultural",
  },
  {
    id: "prod-003",
    name: "Corn Mill",
    image: "/corn mill.png",
    price: "Rs. 22,000",
    rating: 4.5,
    reviews: 38,
    description:
      "Efficient corn mill for grinding corn and other grains. Ideal for small to medium-scale farming operations.",
    features: [
      "High grinding capacity of 50-100kg per hour",
      "Adjustable fineness settings",
      "Durable cast iron construction",
      "Low noise operation",
      "Easy to clean and maintain",
    ],
    specifications: {
      "Motor Power": "2200W",
      Voltage: "220V/50Hz",
      Capacity: "50-100kg/hour",
      Speed: "2800rpm",
      Material: "Cast Iron",
      Dimensions: "50 x 40 x 90cm",
      Weight: "45kg",
    },
    availability: "In Stock",
    category: "agricultural",
  },
  {
    id: "prod-004",
    name: "Tiller",
    image: "/tiller.png",
    price: "Rs. 45,000",
    isNew: true,
    rating: 4.9,
    reviews: 29,
    description:
      "Powerful tiller for effective soil preparation and cultivation. Features adjustable tilling width and depth for versatile operation.",
    features: [
      "Powerful 7HP engine for tough soil conditions",
      "Adjustable working width from 36cm to 90cm",
      "6 forward and 2 reverse gears",
      "Heavy-duty steel tines for durability",
      "Ergonomic handles with vibration dampening",
    ],
    specifications: {
      Engine: "7HP, 4-stroke",
      "Fuel Type": "Petrol",
      "Tilling Width": "36-90cm",
      "Tilling Depth": "Up to 30cm",
      Transmission: "Chain drive",
      Weight: "85kg",
      Warranty: "2 years",
    },
    availability: "In Stock",
    category: "agricultural",
  },

  // Carpentry Tools
  {
    id: "prod-005",
    name: "Router",
    image: "/Router.png",
    price: "Rs. 12,000",
    rating: 4.6,
    reviews: 38,
    description:
      "Professional wood router with variable speed control and precision depth adjustment for detailed woodworking.",
    features: [
      "1200W powerful motor",
      "Variable speed control",
      "Micro depth adjustment",
      "Soft start feature",
      "Multiple base plates included",
    ],
    specifications: {
      "Power Input": "1200W",
      "No-Load Speed": "8,000-24,000rpm",
      "Collet Size": "1/4 inch and 1/2 inch",
      Weight: "3.8kg",
      Warranty: "1 year",
    },
    availability: "In Stock",
    category: "carpentry",
  },
  {
    id: "prod-006",
    name: "Planer",
    image: "/pleansure.png",
    price: "Rs. 9,800",
    isNew: true,
    rating: 4.7,
    reviews: 29,
    description:
      "High-performance electric planer for smooth and precise woodworking.",
    features: [
      "Powerful 900W motor",
      "Adjustable cutting depth",
      "82mm planing width",
      "Parallel fence included",
      "Dust extraction port",
    ],
    specifications: {
      "Power Input": "900W",
      "No-Load Speed": "16,000rpm",
      "Planing Width": "82mm",
      Weight: "3.2kg",
      Warranty: "1 year",
    },
    availability: "In Stock",
    category: "carpentry",
  },
  {
    id: "prod-007",
    name: "Drill Machine",
    image: "/drill machine.png", // Updated drill machine image
    price: "Rs. 8,500",
    rating: 4.5,
    reviews: 45,
    description:
      "Professional-grade drill machine with variable speed control and hammer function.",
    features: [
      "850W powerful motor",
      "Variable speed control",
      "Hammer function",
      "13mm keyless chuck",
      "360° auxiliary handle",
    ],
    specifications: {
      "Power Input": "850W",
      "No-Load Speed": "0-3000rpm",
      "Chuck Capacity": "13mm",
      Weight: "2.3kg",
      Warranty: "1 year",
    },
    availability: "In Stock",
    category: "carpentry",
  },
  {
    id: "prod-008",
    name: "Marble Cutter",
    image: "/marble cutter.jpg",
    price: "Rs. 7,500",
    rating: 4.6,
    reviews: 33,
    description:
      "Professional marble cutter with high-speed motor and water cooling system.",
    features: [
      "1300W powerful motor",
      "125mm diamond cutting disc",
      "Water cooling system",
      "Dust extraction port",
      "Safety lock button",
    ],
    specifications: {
      "Power Input": "1300W",
      "No-Load Speed": "12,000rpm",
      "Disc Diameter": "125mm",
      Weight: "3.5kg",
      Warranty: "1 year",
    },
    availability: "In Stock",
    category: "carpentry",
  },

  // Plumbing & Irrigation
  {
    id: "prod-010",
    name: "Pipe Connectors",
    image: "/pipe connector.jpg", // Updated pipe connectors image
    price: "Rs. 450",
    rating: 4.4,
    reviews: 52,
    description:
      "High-quality pipe connectors for plumbing and irrigation systems made from durable materials.",
    features: [
      "Made from durable PVC material",
      "Available in various sizes",
      "Leak-proof design with rubber seals",
      "Easy to install without special tools",
      "Resistant to corrosion and chemicals",
    ],
    specifications: {
      Material: "PVC",
      "Sizes Available": '1/2", 3/4", 1", 1.5", 2"',
      "Pressure Rating": "PN16",
      "Package Contents": "10 pieces",
      Warranty: "6 months",
    },
    availability: "In Stock",
    category: "plumbing",
  },
  {
    id: "prod-011",
    name: "Sprinkler System",
    image: "/sprinkler.png",
    price: "Rs. 8,500",
    isNew: true,
    rating: 4.7,
    reviews: 38,
    description:
      "Complete sprinkler system for efficient irrigation. Ideal for farms, gardens, and landscaping applications.",
    features: [
      "360-degree coverage",
      "Adjustable spray patterns",
      "Durable construction",
      "Easy installation",
      "Water-efficient design",
    ],
    specifications: {
      Coverage: "Up to 300m²",
      "Operating Pressure": "2-4 bar",
      Material: "Heavy-duty plastic",
      "Spray Distance": "3-12m",
      Package: "Complete set with connectors",
      Warranty: "1 year",
    },
    availability: "In Stock",
    category: "plumbing",
  },
  {
    id: "prod-012",
    name: "Drip Irrigation Kit",
    image: "/irrigation.png",
    price: "Rs. 6,500",
    rating: 4.8,
    reviews: 29,
    description:
      "Complete drip irrigation kit for efficient water usage in gardens and farms.",
    features: [
      "Covers up to 1000 square feet of garden area",
      "Water-saving design reduces consumption by up to 70%",
      "Includes drip tape with emitters",
      "Comes with filters, pressure regulators, and connectors",
      "Easy to install and maintain",
    ],
    specifications: {
      "Coverage Area": "Up to 1000 sq ft",
      "Drip Tape Length": "100m",
      "Emitter Spacing": "30cm",
      "Kit Contents": "Drip tape, filters, connectors, pressure regulator",
      Warranty: "1 year",
    },
    availability: "In Stock",
    category: "plumbing",
  },

  // Solar Products
  {
    id: "prod-013",
    name: "Solar Panel 150W",
    image: "/Untitled.png", // Updated solar panel image
    price: "Rs. 18,000",
    isNew: true,
    rating: 4.9,
    reviews: 42,
    description:
      "High-efficiency 150W solar panel for sustainable energy generation.",
    features: [
      "150W monocrystalline solar panel with 21% efficiency",
      "Tempered glass with anti-reflective coating",
      "Aluminum frame for durability and corrosion resistance",
      "IP65 rated junction box for weather protection",
      "25-year performance warranty",
    ],
    specifications: {
      "Power Output": "150W",
      "Cell Type": "Monocrystalline",
      Efficiency: "21%",
      Dimensions: "1480 x 670 x 35mm",
      Weight: "12kg",
      Warranty: "25 years",
    },
    availability: "In Stock",
    category: "solar",
  },
  {
    id: "prod-014",
    name: "Solar Battery",
    image: "/battrey.png",
    price: "Rs. 22,500",
    rating: 4.8,
    reviews: 36,
    description:
      "High-capacity solar battery for reliable energy storage. Perfect for solar power systems and backup power solutions.",
    features: [
      "Deep cycle technology",
      "Maintenance-free design",
      "Long service life",
      "High discharge rate",
      "Temperature resistant",
    ],
    specifications: {
      Capacity: "100Ah",
      Voltage: "12V",
      Type: "Deep Cycle AGM",
      "Cycle Life": "1500+ cycles",
      Weight: "30kg",
      Warranty: "3 years",
    },
    availability: "In Stock",
    category: "solar",
  },
  {
    id: "prod-015",
    name: "Solar Inverter",
    image: "/inverters.png",
    price: "Rs. 15,800",
    rating: 4.7,
    reviews: 28,
    description:
      "Pure sine wave solar inverter for converting DC power from solar panels to AC power.",
    features: [
      "1000W pure sine wave output for sensitive electronics",
      "Built-in MPPT charge controller for efficient charging",
      "LCD display for system monitoring",
      "Multiple protection features for safety",
      "Compact and lightweight design",
    ],
    specifications: {
      Power: "1000W",
      "Input Voltage": "12V DC",
      "Output Voltage": "220V AC",
      Efficiency: ">90%",
      Weight: "8kg",
      Warranty: "2 years",
    },
    availability: "In Stock",
    category: "solar",
  },
  {
    id: "prod-009",
    name: "Solar Water Pump",
    image: "/water pump.png", // Updated water pump image
    price: "Rs. 35,000",
    rating: 4.6,
    reviews: 45,
    description:
      "High-performance solar water pump for irrigation and water supply needs. Features durable construction and efficient operation.",
    features: [
      "Solar-powered operation for energy savings",
      "Stainless steel construction",
      "Multiple connection options",
      "Low maintenance design",
      "Energy efficient operation",
    ],
    specifications: {
      Power: "1.5HP",
      "Max Flow Rate": "60L/min",
      "Max Head": "40m",
      "Solar Panel": "2 x 150W panels included",
      Material: "Stainless Steel",
      Warranty: "1 year",
    },
    availability: "In Stock",
    category: "solar", // Changed category to solar
  },
];
